#!/bin/bash -x
LOG_PATH=~/play2/logs/prebuild.log

echo "Pre Building Blog to OpenShift..."

# cd $OPENSHIFT_REPO_DIR >> $LOG_PATH
# rm -rf blog >> $LOG_PATH
# mkdir blog >> $LOG_PATH

echo "Pre Building done!"
