#!/bin/bash -x
LOG_PATH=$OPENSHIFT_SCALA_LOG_DIR/prebuild.log

echo "Pre Building Blog to OpenShift..."

cd $OPENSHIFT_REPO_DIR
rm -rf blog
mkdir blog
cd blog
git clone ${GIT_REPO_BLOG} .

echo "Pre Building done!"
