#!/bin/bash -x
LOG_PATH=$OPENSHIFT_SCALA_LOG_DIR/stop.log

echo "Stopping OpenShift App..." >> $LOG_PATH

kill $(cat $OPENSHIFT_REPO_DIR/misc/pid.pid)  >> $LOG_PATH
rm $OPENSHIFT_REPO_DIR/misc/pid.pid >> $LOG_PATH
exit 0

echo "Stopped" >> $LOG_PATH
