title: Roped In
subTitle: Serving God in Germany
author: James and Beth Roper

disqus_shortname: ropedin

theme: themes.Theme$

description: |
  <div style="text-align: center; margin: 10px 0;"><img src="images/jamesbeth.jpg"/></div>
  <p>
  Hi! We're James and Beth, we are a couple that helped plant a church in Berlin, Germany.
  This is our story. 
  </p>
  <p>
  You can read more about us <a href="pages/about.html">here</a>.
